name: voice_recorder
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  # another_audio_recorder: ^1.1.0
  path_provider: ^2.1.3
  file: ^7.0.0
  audioplayers: ^6.0.0
  permission_handler: ^11.3.1
  intl: ^0.19.0
  youtube_player_flutter: ^9.0.1
  flutter_launcher_icons: ^0.13.1
  fl_chart: ^0.68.0
  flutter_sound: ^9.2.13
  audio_waveforms: ^1.0.5
  share_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter_icons:
  android: true
  image_path: "assets/images/logo.png"
  adaptive_icon_foreground: "assets/images/logo.png"
  # ios: true
  adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/madina.png
    - assets/images/play.gif
    - assets/images/play1.gif
    - assets/images/play2.gif
    - assets/images/logo.png